config {
    type: "incremental",
    schema: "silver",
    name: "bronze_checkpoint",
    uniqueKey: ["table_name"],
    tags: ["silver", "lookup", "daily"],
    description: "Theo dõi ngày dữ liệu mới nhất của các bảng ở lớp bronze."
}

js {
  const tables_to_track = [
    "CORTSUB_ACCOUNT","CORTASSET_EXT","CORTASSET","CORTCUSTOMER", "BRKTBROKER",
    "MRGTDEBIT_CONTRACT_HIST", "CORTCASH_MOVEMENT_HISTORY", "MSTTSECURITIES",
    "MSTTMARKET", "CORTSEC_BALANCE_HISTORY", "ORDTORDER_HIST", "RHTTRIGHT_INFO"
  ];
  
  const default_start_date = '2024-01-01';
}

${when(!incremental(), 
    tables_to_track.map(table => 
        `SELECT '${table}' AS table_name, DATE('${default_start_date}') AS latest_date, CURRENT_TIMESTAMP() AS _updated_at`
    ).join("\nUNION ALL ")
)}

${when(incremental(), `
  WITH expected_tables AS (
    ${tables_to_track.map(table => `SELECT '${table}' AS table_name`).join("\nUNION ALL ")}
  )
  SELECT 
    e.table_name, 
    DATE('${default_start_date}') AS latest_date, 
    CURRENT_TIMESTAMP() AS _updated_at
  FROM expected_tables e
  LEFT JOIN ${self()} s ON e.table_name = s.table_name
  WHERE s.table_name IS NULL
`)}