config {
  // ===========================================================================
  // BƯỚC 1: Config metadata của file
  // ===========================================================================
  type: "view",
  schema: "silver",
  name: "fact_subaccount_daily_asset_value",
  description: "View giá trị tài sản hàng ngày của tiểu khoản",
  tags: ["silver", "fact", "asset_value", "view"]
}

js {
  // ============================================================================
  // BƯỚC 2. Điền thông tin về nguồn dữ liệu, key và độ chi tiết
  // ============================================================================
  const source_schema = "silver";                       // Dataset chứa bảng stage nguồn
  const source_table = "stage_cortasset";               // Tên bảng stage nguồn
  
  const natural_key = ["sub_acco_no", 'business_date'];
  const tech_key = "sub_acco_cd";

  // ============================================================================
  // BƯỚC 3. Điền các cột ở bảng stage mà cần có ở bảng view
  // ============================================================================
  const cols = [
    "business_date", "sub_acco_cd", "sub_acco_no", "is_deleted", "sub_acco_type", 
    "cust_cd", "cust_no", "cust_name", "branch_cd", "transaction_cd", "broker_cd", 
    "source_cd", "cust_group_id", "warning_level", "warning_num",
    "cash_amt", "sec_val", "sec_mrg_val", "sec_pending_val", "sec_mrg_pending_val", 
    "cash_pending_amt", "advance_amt", "bought_not_post_amt", "dividend_cash_amt", 
    "dividend_sec_val", "dividend_right_val", "other_asset_val", "debit_margin_amt", 
    "debit_coop_amt", "debit_debt_amt", "debit_mor_amt", "debit_other_amt", 
    "debit_temp_amt", "total_interest_amt", "debit_margin_expired", "debit_coop_expired", 
    "debit_mor_expired", "cash_block_amt", "credit_limit", "debt_interest_avail_payment", 
    "need_to_addition_cash", "need_to_addition_sec", "need_to_sell", "total_asset", 
    "total_mrg_asset", "total_debit", "margin_rate", "credit_cash_amt", "credit_sec_amt", 
    "t0_buy_amt", "t1_buy_amt", "t2_buy_amt", "t0_sell_amt", "t1_sell_amt", "t2_sell_amt", 
    "dividend_cash_market_amt", "dividend_sec_market_amt", "nav_bi"
  ];

  // ============================================================================
  // BƯỚC 4: Một số biến hỗ trợ logic (không cần đụng vào)
  // ============================================================================
  const source_ref = ref(source_schema, source_table);
}

-- ===========================================================================
-- LOGIC SQL (không cần đụng vào)
-- ===========================================================================

SELECT
    ${cols.join(",\n    ")}
FROM ${source_ref}
QUALIFY
ROW_NUMBER() OVER (PARTITION BY ${natural_key.join(", ")} ORDER BY ${tech_key} DESC) = 1