config {
    type: "incremental",
    schema: "silver",
    name: "fact_cash_movement",
    description: "Bảng Fact lịch sử giao dịch tiền của khách hàng từ hệ thống Core",
    tags: ["silver", "fact", "daily", "cash"],
    uniqueKey: ["fact_cash_movement_key"],
    bigquery: {
        partitionBy: "allo_date"
    }
}

pre_operations {
  -- 1. Xác định thời gian chạy
  DECLARE run_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP();
  -- 2. Xác định target_date
  DECLARE target_date DATE;
  SET target_date = (
    ${dataform.projectConfig.vars.target_date 
      ? `DATE('${dataform.projectConfig.vars.target_date}')` 
      : `(SELECT MAX(allo_date) FROM ${ref("silver", "stage_cortcash_movement_history")})`
    }
  );
}
WITH base_fact AS (
    SELECT
        -- Keys & Identifiers
        ${func.generate_hash(["'VGaia'", "CAST(allo_date AS STRING)", "CAST(ref_no AS STRING)"])} AS fact_cash_movement_key,
        allo_date,
        ref_no,
        is_deleted,
        cust_cd,
        cust_no,
        sub_acco_cd,
        sub_acco_no,

        -- Transaction Details
        entry_date,
        approvement_id,
        group_category,
        task_cd,
        src_date,
        src_no,
        src_transaction_cd,
        curr_cd,

        -- Amounts
        begin_amount,
        amount,
        amount_type,
        trade_type,
        after_amount,

        -- Status & Utility
        util_cd,
        util_cash_id,
        status,
        transaction_cd,
        internal_balance_code,
        doc,

        -- Comments
        remarks,
        memo
    FROM ${ref("silver", "stage_cortcash_movement_history")}
    WHERE allo_date = target_date
)

SELECT
    ${when(incremental(), `COALESCE(target._ingested_at, run_time)`, `run_time`)} AS _ingested_at,
    run_time AS _updated_at,
    stg.*
FROM base_fact AS stg
${when(incremental(), 
  `LEFT JOIN ${self()} AS target 
    ON stg.fact_cash_movement_key = target.fact_cash_movement_key`
)}