-- =====================================================================================
-- SILVER STAGE VIEW
-- =====================================================================================

config {
    // ===========================================================================
    // BƯỚC 0: Config metadata của file
    // ===========================================================================
    type: "view", 
    schema: "silver",
    name: "stage_cortasset",
    tags: ["silver", "stage", "daily", "asset_value"]
}

js {
    // ===========================================================================
    // BƯỚC 1: Xác định nguồn dữ liệu
    // ===========================================================================
    const source_schema = "bronze";
    const source_table = "CORTASSET";
    const source_partition_col = 'BUSINESS_DATE';
    const target_partition_col = 'business_date';

    // ===========================================================================
    // BƯỚC 2: Xác định mức độ chi tiết và logic để deduplicate
    // ===========================================================================
    const unique_key_cols = ["SUB_ACCO_CD", "BUSINESS_DATE"];
    const dedupe_order_by = [
        {field: "InsertTime", sort: "DESC"},
        {field: "UPD_DATE_TIME", sort: "DESC"}
    ];
    

    // ===========================================================================
    // BƯỚC 3: Phân loại các trường để clean và chuẩn hóa
    // ===========================================================================
    const date_cols = ["BUSINESS_DATE", "InsertDate"];
    const numeric_date_cols = [];
    const boolean_cols = [
        {source: "DEL_CD", field_name: "is_deleted", true_value: 9},
    ];
    const string_cols = [
        "SUB_ACCO_NO", "CUST_NO", "CUST_NAME", "BRANCH_CD", "TRANSACTION_CD", 
        "BROKER_CD", "SOURCE_CD", 
    ];
    const integer_cols = [
        "SUB_ACCO_CD", "SUB_ACCO_TYPE", "CUST_CD", "CUST_GROUP_ID", "WARNING_LEVEL", "WARNING_NUM"
    ];
    const numeric_cols = [
        "CASH_AMT", "SEC_VAL", "SEC_MRG_VAL", "SEC_PENDING_VAL", "SEC_MRG_PENDING_VAL", 
        "CASH_PENDING_AMT", "ADVANCE_AMT", "BOUGHT_NOT_POST_AMT", "DIVIDEND_CASH_AMT", 
        "DIVIDEND_SEC_VAL", "DIVIDEND_RIGHT_VAL", "OTHER_ASSET_VAL", "DEBIT_MARGIN_AMT", 
        "DEBIT_COOP_AMT", "DEBIT_DEBT_AMT", "DEBIT_MOR_AMT", "DEBIT_OTHER_AMT", 
        "DEBIT_TEMP_AMT", "TOTAL_INTEREST_AMT", "DEBIT_MARGIN_EXPIRED", "DEBIT_COOP_EXPIRED", 
        "DEBIT_MOR_EXPIRED", "CASH_BLOCK_AMT", "CREDIT_LIMIT", "DEBT_INTEREST_AVAIL_PAYMENT", 
        "NEED_TO_ADDITION_CASH", "NEED_TO_ADDITION_SEC", "NEED_TO_SELL", "TOTAL_ASSET", 
        "TOTAL_MRG_ASSET", "TOTAL_DEBIT", "MARGIN_RATE", "CREDIT_CASH_AMT", "CREDIT_SEC_AMT", 
        "T0_BUY_AMT", "T1_BUY_AMT", "T2_BUY_AMT", "T0_SELL_AMT", "T1_SELL_AMT", "T2_SELL_AMT", 
        "DIVIDEND_CASH_MARKET_AMT", "DIVIDEND_SEC_MARKET_AMT", "NAV_BI"
    ];
    const cleaned_cols = [
        "REG_DATE_TIME", "UPD_DATE_TIME", "InsertTime", "REG_USER_ID", "UPD_USER_ID"
    ];

    // ===========================================================================
    // BƯỚC 4: Thêm trường mới tùy biến
    // ===========================================================================
    const custom_cols = [];

    // ===========================================================================
    // BƯỚC 5: Kiểm tra xem target_partition_col đã có chưa
    // ===========================================================================
    const isPartitionInDateCols = date_cols.some(
        col => col.toLowerCase() === target_partition_col.toLowerCase()
    );
}

-- ===========================================================================
-- LOGIC SQL
-- ===========================================================================
SELECT
${
    [
        // Thêm partition column nếu chưa có ở dưới
        ...(!isPartitionInDateCols ? [`${func.cleanNullDate(source_partition_col)} AS ${target_partition_col}`] : []),
        
        // Thêm logic tùy biến
        ...custom_cols.map(c => `${c.field_query} AS ${c.field_name}`),

        // Clean và chuẩn hóa kiểu dữ liệu
        ...date_cols.map(col => `${func.cleanNullDate(col)} AS ${col.toLowerCase()}`),
        ...numeric_date_cols.map(col => `${func.parseNumericDate(col)} AS ${col.toLowerCase()}`),
        ...string_cols.map(col => `${func.cleanNullString(col)} AS ${col.toLowerCase()}`),
        ...integer_cols.map(col => `CAST(${col} AS INT64) AS ${col.toLowerCase()}`),
        ...numeric_cols.map(col => `CAST(${col} AS NUMERIC) AS ${col.toLowerCase()}`),
        ...boolean_cols.map(b => `CAST(${b.source} AS INT64) = ${b.true_value} AS ${b.field_name}`),
        ...cleaned_cols.map(col => `${col} AS ${col.toLowerCase()}`)
    ].join(",\n        ")
}
FROM ${ref(source_schema, source_table)}

-- Deduplicate để đảm bảo tính duy nhất của View
QUALIFY
ROW_NUMBER() OVER (
    PARTITION BY ${unique_key_cols.join(", ")} 
    ORDER BY ${dedupe_order_by.map(o => `${o.field} ${o.sort}`).join(", ")}
) = 1