config {
    // ===========================================================================
    // BƯỚC 1: Config metadata của file
    // ===========================================================================
    type: "table", // table thay vì view để chỉnh partition theo InsertDate
    schema: "silver",
    name: "stage_rhttright_info",
    tags: ["silver", "stage", "daily", "right"],
    bigquery: {partitionBy: "snapshot_date"}
}

js {
    // ===========================================================================
    // BƯỚC 2: Xác định nguồn dữ liệu
    // ===========================================================================
    const source_schema = "bronze";
    const source_table = "RHTTRIGHT_INFO"; 
    const source_partition_col = 'InsertDate';
    const target_partition_col = 'snapshot_date';
    
    // ===========================================================================
    // BƯỚC 3: Xác định mức độ chi tiết và logic để deduplicate
    // ===========================================================================
    const unique_key_cols = ["VSD_ID", 'InsertDate'];
    const dedupe_order_by = [
        {field: "InsertTime", sort: "DESC"},
        {field: "ALLO_DATE", sort: "DESC"},
        {field: "REF_NO", sort: "DESC"}
    ];
    
    // ===========================================================================
    // BƯỚC 4: Phân loại các trường để clean và chuẩn hóa
    // ===========================================================================
    const date_cols = [
        "NO_RIGHT_DATE",
        "OWNER_FIX_DATE",
        "RIGHT_EXC_DATE",
        "EXPECTED_EXC_DATE",
        "OWNER_LIST_PEPORT_DATE",
        "BEGIN_TRADE_DATE",
        "END_TRADE_DATE",
        "BEGIN_REG_DATE",
        "END_REG_DATE",
        "BEGIN_TRANS_DATE",
        "END_TRANS_DATE"
    ];
    const numeric_date_cols = [];
    const boolean_cols = [
        {source: "DEL_CD", field_name: "is_deleted", true_value: 9},
        {source: "IS_SPLIT_TYPE_POST", field_name: "is_split_type_post", true_value: 1}
    ];
    const string_cols = [
        "VSD_ID",
        "SEC_CD",
        "TARGET_SEC_CD",
        "SEME",
        "TRANSACTION_CD",
        "REMARKS",
        "APPROVED_USER_ID",
        "REG_USER_ID",
        "UPD_USER_ID"
    ];
    const integer_cols = [
        "RIGHT_TYPE",
        "SEC_STATE",
        "MARKET_CD",
        "ROUNDTYPE",
        "DECIMAL_PLACE",
        "ODD_DECIMAL_PLACE",
        "FORCE_ALTER",
        "STATUS"
    ];
    const numeric_cols = [
        "REF_NO",
        "CAL_PENDING_SEC",
        "RATES1",
        "RATED1",
        "RATES",
        "RATED",
        "PRICE",
        "ROUND_PRICE",
        "INVEST_PRICE",
        "MAX_RATE",
        "TAX_RATE",
        "TRANSFER_FEE"
    ];
    const cleaned_cols = [
        "APPROVED_DATE_TIME",
        "REG_DATE_TIME",
        "UPD_DATE_TIME",
        "InsertTime",
        "ALLO_DATE",
        'InsertDate'
    ];

    // ===========================================================================
    // BƯỚC 5: Thêm trường mới tùy biến
    // ===========================================================================
    const custom_cols = [];

    // ===========================================================================
    // BƯỚC 6: Một số biến phục vụ cho logic file (không cần đụng vào)
    // ===========================================================================
    const isPartitionInCleanedCols = cleaned_cols.some(
        col => col.toLowerCase() === target_partition_col.toLowerCase()
    );
    const source_ref = ref(source_schema, source_table);
    const checkpoint_ref = ref("silver", "bronze_checkpoint");
}

-- ===========================================================================
-- LOGIC SQL (không cần đụng vào)
-- ===========================================================================
SELECT
${
    [
        // Thêm partition column nếu chưa có ở dưới
        ...(!isPartitionInCleanedCols ? [`${source_partition_col} AS ${target_partition_col}`] : []),
        
        // Thêm logic tùy biến
        ...custom_cols.map(c => `${c.field_query} AS ${c.field_name}`),

        // Clean và chuẩn hóa kiểu dữ liệu
        ...date_cols.map(col => `${func.cleanNullDate(col)} AS ${col.toLowerCase()}`),
        ...numeric_date_cols.map(col => `${func.parseNumericDate(col)} AS ${col.toLowerCase()}`),
        ...string_cols.map(col => `${func.cleanNullString(col)} AS ${col.toLowerCase()}`),
        ...integer_cols.map(col => `CAST(${col} AS INT64) AS ${col.toLowerCase()}`),
        ...numeric_cols.map(col => `CAST(${col} AS NUMERIC) AS ${col.toLowerCase()}`),
        ...boolean_cols.map(b => `CAST(${b.source} AS INT64) = ${b.true_value} AS ${b.field_name}`),
        ...cleaned_cols.map(col => `${col} AS ${col.toLowerCase()}`)
    ].join(",\n        ")
}
FROM ${ref(source_schema, source_table)}

-- Deduplicate để đảm bảo tính duy nhất của View
QUALIFY
ROW_NUMBER() OVER (
    PARTITION BY ${unique_key_cols.join(", ")} 
    ORDER BY ${dedupe_order_by.map(o => `${o.field} ${o.sort}`).join(", ")}
) = 1

post_operations {
    ${func.updateCheckpoint(source_table, source_ref, source_partition_col, checkpoint_ref)}
}