-- =====================================================================================
-- SILVER STAGE VIEW
-- =====================================================================================

config {
    // ===========================================================================
    // BƯỚC 0: Config metadata của file
    // ===========================================================================
    type: "view", 
    schema: "silver",
    name: "stage_cortasset_ext",
    tags: ["silver", "stage", "daily", "subaccount"]
}

js {
    // ===========================================================================
    // BƯỚC 1: Xác định nguồn dữ liệu
    // ===========================================================================
    const source_schema = "bronze";
    const source_table = "CORTASSET_EXT";
    const source_partition_col = 'BUSINESS_DATE';
    const target_partition_col = 'business_date';

    // ===========================================================================
    // BƯỚC 2: Xác định mức độ chi tiết và logic để deduplicate
    // ===========================================================================
    const unique_key_cols = ["SUB_ACCO_CD", "BUSINESS_DATE"];
    const dedupe_order_by = [
        {field: "InsertTime", sort: "DESC"},
        {field: "UPD_DATE_TIME", sort: "DESC"}
    ];
    

    // ===========================================================================
    // BƯỚC 3: Phân loại các trường để clean và chuẩn hóa
    // ===========================================================================
    const date_cols = [];
    const numeric_date_cols = [];
    const boolean_cols = [
        {source: "DEL_CD", field_name: "is_deleted", true_value: 9},
        {source: "IS_AUTO_ADVANCE", field_name: "is_auto_advance", true_value: 1},
        {source: "IS_AUTO_MORTGAGE", field_name: "is_auto_mortgage", true_value: 1}
    ];
    const string_cols = [
        "MARGIN_BROKER_CD", 
    ];
    const integer_cols = [
        "SUB_ACCO_CD"
    ];
    const numeric_cols = [
        "CASH_PENDING_BLOCK_AMT", "CASH_PENDING_PAY_AMT", "SEC_PENDING_BLOCK_AMT", 
        "SEC_MRG_PENDING_BLOCK_AMT", "ADVANCE_AVAIL", "REQUIRE_BOUGHT_UNPOST_AMT", 
        "MORTGAGE_AVAIL_AUTO", "MARGIN_LIMIT_GRP", "MARGIN_LIMIT"
    ];
    const float_cols = [
        "RETENTION_RATE", "TN_RATE", "MARGIN_RATE", "WARNING_RATE", 
        "CALL_RATE", "WITHDRAW_RATE"
    ];
    const cleaned_cols = [
        "BUSINESS_DATE", "InsertDate", "InsertTime",
        "REG_DATE_TIME", "UPD_DATE_TIME", "REG_USER_ID", "UPD_USER_ID"
    ];

    // ===========================================================================
    // BƯỚC 4: Thêm trường mới tùy biến
    // ===========================================================================
    const custom_cols = [];

    // ===========================================================================
    // BƯỚC 5: Kiểm tra xem target_partition_col đã có chưa
    // ===========================================================================
    const isPartitionInCleanedCols = cleaned_cols.some(
        col => col.toLowerCase() === target_partition_col.toLowerCase()
    );
}

-- ===========================================================================
-- LOGIC SQL
-- ===========================================================================
SELECT
${
    [
        // Thêm partition column nếu chưa có ở dưới
        ...(!isPartitionInCleanedCols ? [`${source_partition_col} AS ${target_partition_col}`] : []),
        
        // Thêm logic tùy biến
        ...custom_cols.map(c => `${c.field_query} AS ${c.field_name}`),

        // Clean và chuẩn hóa kiểu dữ liệu
        ...date_cols.map(col => `${func.cleanNullDate(col)} AS ${col.toLowerCase()}`),
        ...numeric_date_cols.map(col => `${func.parseNumericDate(col)} AS ${col.toLowerCase()}`),
        ...string_cols.map(col => `${func.cleanNullString(col)} AS ${col.toLowerCase()}`),
        ...integer_cols.map(col => `CAST(${col} AS INT64) AS ${col.toLowerCase()}`),
        ...numeric_cols.map(col => `CAST(${col} AS NUMERIC) AS ${col.toLowerCase()}`),
        ...float_cols.map(col => `CAST(${col} AS FLOAT64) AS ${col.toLowerCase()}`),
        ...boolean_cols.map(b => `CAST(${b.source} AS INT64) = ${b.true_value} AS ${b.field_name}`),
        ...cleaned_cols.map(col => `${col} AS ${col.toLowerCase()}`)
    ].join(",\n        ")
}
FROM ${ref(source_schema, source_table)}

-- Deduplicate để đảm bảo tính duy nhất của View
QUALIFY
ROW_NUMBER() OVER (
    PARTITION BY ${unique_key_cols.join(", ")} 
    ORDER BY ${dedupe_order_by.map(o => `${o.field} ${o.sort}`).join(", ")}
) = 1