-- =====================================================================================
-- SILVER STAGE VIEW
-- =====================================================================================

config {
    // ===========================================================================
    // BƯỚC 0: Config metadata của file
    // ===========================================================================
    type: "view", 
    schema: "silver",
    name: "stage_cortsub_account",
    tags: ["silver", "stage", "daily", "subaccount"]
}

js {
    // ===========================================================================
    // BƯỚC 1: Xác định nguồn dữ liệu
    // ===========================================================================
    const source_schema = "bronze";
    const source_table = "CORTSUB_ACCOUNT";
    const source_partition_col = 'InsertDate';
    const target_partition_col = 'snapshot_date';

    // ===========================================================================
    // BƯỚC 2: Xác định mức độ chi tiết và logic để deduplicate
    // ===========================================================================
    const unique_key_cols = ["SUB_ACCO_CD", "InsertDate"];
    const dedupe_order_by = [
        {field: "InsertTime", sort: "DESC"},
        {field: "UPD_DATE_TIME", sort: "DESC"}
    ];
    

    // ===========================================================================
    // BƯỚC 3: Phân loại các trường để clean và chuẩn hóa
    // ===========================================================================
    const date_cols = [];
    const numeric_date_cols = ["OPEN_DATE", "CLOSE_DATE", "REOPEN_DATE"];
    const boolean_cols = [
        {source: "DEL_CD", field_name: "is_deleted", true_value: 9},
    ];
    const string_cols = [
        "CURR_CD", "SUB_ACCO_NO", "BANK_CD", "BANK_BRANCH_CD", 
        "BANK_ACCO_NUMBER", "BANK_ACCO_NAME", "BANK_ACCO_ID_NO", 
        "CONTRACT_NO", "BROKER_CD", "TRADE_ACCO_NO", "SOURCE_CD", 
        "SOURCE_SNAME", "REMARKS", "REG_USER_ID", "UPD_USER_ID"
    ];
    const integer_cols = [
        "SUB_ACCO_CD", "CUST_CD", "ALGOS_TYPE", "ACCO_TYPE", "TYPE_FLG", 
        "NOT_UPDATE_BY_CUST", "BANK_FLG", "SOURCE_CHANNEL", "ACCO_STS", 
        "ACCO_FLG", "STATUS"
    ];
    const numeric_cols = [];
    const cleaned_cols = [
        "REG_DATE_TIME", "UPD_DATE_TIME", "InsertTime", "InsertDate"
    ];

    // ===========================================================================
    // BƯỚC 4: Thêm trường mới tùy biến
    // ===========================================================================
    const custom_cols = [];

    // ===========================================================================
    // BƯỚC 5: Kiểm tra xem target_partition_col đã có chưa
    // ===========================================================================
    const isPartitionInCleanedCols = cleaned_cols.some(
        col => col.toLowerCase() === target_partition_col.toLowerCase()
    );
}

-- ===========================================================================
-- LOGIC SQL
-- ===========================================================================
SELECT
${
    [
        // Thêm partition column nếu chưa có ở dưới
        ...(!isPartitionInCleanedCols ? [`${source_partition_col} AS ${target_partition_col}`] : []),
        
        // Thêm logic tùy biến
        ...custom_cols.map(c => `${c.field_query} AS ${c.field_name}`),

        // Clean và chuẩn hóa kiểu dữ liệu
        ...date_cols.map(col => `${func.cleanNullDate(col)} AS ${col.toLowerCase()}`),
        ...numeric_date_cols.map(col => `${func.parseNumericDate(col)} AS ${col.toLowerCase()}`),
        ...string_cols.map(col => `${func.cleanNullString(col)} AS ${col.toLowerCase()}`),
        ...integer_cols.map(col => `CAST(${col} AS INT64) AS ${col.toLowerCase()}`),
        ...numeric_cols.map(col => `CAST(${col} AS NUMERIC) AS ${col.toLowerCase()}`),
        ...boolean_cols.map(b => `CAST(${b.source} AS INT64) = ${b.true_value} AS ${b.field_name}`),
        ...cleaned_cols.map(col => `${col} AS ${col.toLowerCase()}`)
    ].join(",\n        ")
}
FROM ${ref(source_schema, source_table)}

-- Deduplicate để đảm bảo tính duy nhất của View
QUALIFY
ROW_NUMBER() OVER (
    PARTITION BY ${unique_key_cols.join(", ")} 
    ORDER BY ${dedupe_order_by.map(o => `${o.field} ${o.sort}`).join(", ")}
) = 1