js {
  // 1. CẤU HÌNH NGUỒN DỮ LIỆU
  const source_layer = "silver"
  const source_table = "fact_cash_movement";
  const source_partition_col = "business_date";
  
  // 2. CẤU HÌNH CỘT ĐỂ THỰC HIỆN JOIN KHI TẠO FOREIGN KEY TỪ CÁC ĐỐI TƯỢNG
  const join_date_col = "business_date"

  // 3. DANH SÁCH CÁC TRƯỜNG ĐƯỢC LẤY TỪ BẢNG FACT
  const fact_cols = [
    "business_date", "allo_date", "ref_no", "is_deleted", "cust_cd", "cust_no", "sub_acco_cd", "sub_acco_no",
    "entry_date", "approvement_id", "group_category", "task_cd", "src_date", "src_no",
    "src_transaction_cd", "curr_cd", "begin_amount", "amount", "amount_type", "trade_type",
    "after_amount", "util_cd", "util_cash_id", "status", "transaction_cd",
    "internal_balance_code", "doc", "remarks", "memo"
  ];
}

config {
    type: "incremental",
    schema: "gold",
    name: "cash_movement",
    description: "Bảng thông tin giao dịch tiền đã được denormalized.",
    tags: ["gold", "cash_movement", "fact"],
    uniqueKey: ["cash_movement_key"],
    bigquery: {
        partitionBy: "business_date",
        clusterBy: ["sub_acco_no", "cust_no"]
    },
    columns: {
        // Key và trường partition và metadata
        _ingested_at: "Thời điểm bản ghi được đưa vào Gold layer",
        _updated_at: "Thời điểm bản ghi được cập nhật mới nhất trong Gold layer",
        cash_movement_key: "Khóa chính của bảng Fact, sinh ra từ hash của prefix 'VGaia', allo_date và ref_no",
        business_date: "Ngày nghiệp vụ dùng để partition dữ liệu, lấy từ allo_date của hệ thống nguồn",

        // Thông tin giao dịch
        allo_date: "Ngày hạch toán giao dịch. Kết hợp cùng ref_no để xác định tính duy nhất",
        ref_no: "Số tham chiếu duy nhất của giao dịch trong ngày",
        is_deleted: "Cờ đánh dấu dữ liệu đã bị xóa từ nguồn (9: Deleted)",
        entry_date: "Ngày nhập liệu giao dịch vào hệ thống",
        approvement_id: "ID định danh việc phê duyệt giao dịch",
        group_category: "Phân loại nhóm nghiệp vụ của giao dịch",
        task_cd: "Mã tác vụ hoặc mã loại giao dịch cụ thể",
        src_date: "Ngày phát sinh tại nguồn dữ liệu gốc",
        src_no: "Số tham chiếu tại nguồn dữ liệu gốc",
        src_transaction_cd: "Đơn vị giao dịch của khách hàng",
        transaction_cd: "Đơn vị giao dịch nơi thực hiện nghiệp vụ",

        // Các thông tin về tiền
        curr_cd: "Mã loại tiền tệ của giao dịch",
        begin_amount: "Số dư tiền trước khi thực hiện giao dịch",
        amount: "Số tiền phát sinh của giao dịch",
        amount_type: "Loại tác động số tiền (D: Debit - Ghi nợ, C: Credit - Ghi có)",
        trade_type: "Mã loại giao dịch (1: Debit, 2: Credit)",
        trade_type_name: "Tên loại giao dịch được tra cứu từ bảng dim_attribute_lookup",
        after_amount: "Số dư tiền sau khi thực hiện giao dịch",

        // Status & Attributes
        status: "Mã trạng thái của giao dịch",
        status_name: "Tên trạng thái giao dịch (ví dụ: Đã duyệt, Đã hủy)",
        util_cd: "Mã công cụ hoặc tiện ích đi kèm giao dịch",
        util_cash_id: "ID định danh dòng tiền tiện ích",
        internal_balance_code: "Mã hạch toán tài khoản nội bộ",
        doc: "Thông tin chứng từ liên quan",
        remarks: "Ghi chú vắn tắt về giao dịch",
        memo: "Diễn giải chi tiết nội dung giao dịch",

        // History Keys
        sub_acco_no: "Số hiệu tiểu khoản phát sinh giao dịch",
        subaccount_history_key: "Khóa liên kết đến phiên bản lịch sử tiểu khoản (subaccount_history) có hiệu lực tại thời điểm allo_date",
        
        cust_no: "Số tài khoản khách hàng sở hữu giao dịch",
        customer_history_key: "Khóa liên kết đến phiên bản lịch sử khách hàng (customer_history) có hiệu lực tại thời điểm allo_date",
        
        broker_cd: "Mã nhân viên môi giới quản lý tiểu khoản tại thời điểm giao dịch",
        broker_history_key: "Khóa liên kết đến phiên bản lịch sử môi giới (broker_history) có hiệu lực tại thời điểm allo_date",
    }
}

pre_operations {
  -- 1. Xác định thời gian chạy
  DECLARE run_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

  -- 2. Xác định target_date (Dùng business_date để optimize BigQuery partitions)
  DECLARE target_date DATE;
  SET target_date = (
    ${dataform.projectConfig.vars.target_date 
      ? `DATE('${dataform.projectConfig.vars.target_date}')` 
      : `(SELECT MAX(${source_partition_col}) FROM ${ref(source_layer, source_table)})`
    }
  );
}

WITH staging_data AS (
    SELECT
        -- 1. Xác định key của bảng
        f.fact_cash_movement_key as cash_movement_key,

        -- 2. Các cột từ bảng fact
        ${fact_cols.map(col => `f.${col}`).join(",\n        ")},

        -- 3. Giá trị của các attribte được đánh số
        lkp_trade.attribute_name AS trade_type_name,
        lkp_sts.attribute_name AS status_name,

        -- 4. Natural Keys & History Keys sau khi dùng joinHistory
        f.sub_acco_no,
        s.subaccount_history_key,
        f.cust_no,
        s.customer_history_key,
        s.broker_cd,
        s.broker_history_key
        
    FROM ${ref(source_layer, source_table)} AS f
    
    -- --- JOINS ---
    -- 1. Join để tìm giá trị cho các attribute được đánh số
    LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_trade 
        ON lkp_trade.category = 'CORTCASH_MOVEMENT__TRADE_TYPE' AND f.trade_type = lkp_trade.attribute_code
    LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_sts 
        ON lkp_sts.category = 'CORTCASH_MOVEMENT__STATUS' AND f.status = lkp_sts.attribute_code
        
    -- 2. Dùng hàm joinHistory (ref_bảng, alias_bảng, left_key, right_key, join_date_col) để lấy ra foreign key của các đối tượng
    ${func.joinHistory(ref("gold", "subaccount_history"), "s", "f.sub_acco_no", "sub_acco_no", join_date_col)}
    
    -- --- FILTER ---
    WHERE f.${source_partition_col} = target_date
)

SELECT
    ${when(incremental(), `COALESCE(target._ingested_at, run_time)`, `run_time`)} AS _ingested_at,
    run_time AS _updated_at,
    stg.*
FROM staging_data AS stg
${when(incremental(), 
  `LEFT JOIN ${self()} AS target ON stg.cash_movement_key = target.cash_movement_key`
)}