config {
    type: "incremental",
    schema: "gold",
    name: "debit_contract_daily_balance",
    description: "Daily reporting fact table for debit contract balances, fully denormalized with dimension keys.",
    tags: ["gold", "debit_contract", "fact"],
    uniqueKey: ["debit_contract_daily_balance_key"],
    bigquery: {
        partitionBy: "business_date",
        clusterBy: ["contract_no", "sub_acco_no"]
    }
}

js {
  const source_layer = "silver";
  const source_table = "fact_debit_contract_daily_balance";
  const source_partition_col = "business_date";
  const target_partition_col = "business_date";
  
  const hash_key_name = "debit_contract_daily_balance_key";

  const fact_cols = [
    "is_deleted", "amount", "payed_amount", "payed_interest", 
    "due_interest", "payed_manager", "due_manager", "last_payed_date"
  ];
}

pre_operations {
  -- 1. Khai báo biến
  DECLARE run_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP();
  DECLARE target_date DATE;
  DECLARE start_date DATE;
  DECLARE end_date DATE;

  -- 2. Logic xác định thời gian
  ${incremental() 
    ? `SET target_date = ${dataform.projectConfig.vars.target_date 
        ? `DATE('${dataform.projectConfig.vars.target_date}')` 
        : `(SELECT MAX(${source_partition_col}) FROM ${ref(source_layer, source_table)})`
      };`
    : `SET start_date = ${dataform.projectConfig.vars.start_date 
        ? `DATE('${dataform.projectConfig.vars.start_date}')` 
        : `(SELECT MIN(${source_partition_col}) FROM ${ref(source_layer, source_table)})`
      };
       SET end_date = ${dataform.projectConfig.vars.end_date 
        ? `DATE('${dataform.projectConfig.vars.end_date}')` 
        : `(SELECT MAX(${source_partition_col}) FROM ${ref(source_layer, source_table)})`
      };
       SET target_date = NULL;`
  }

  -- 3. Drop table khi Full Refresh
  ${when(!incremental(),`DROP TABLE IF EXISTS ${self()};`)}
}

WITH staging_data AS (
    SELECT
        -- 1. Fact Keys & Identifiers
        f.${hash_key_name},
        f.business_date,
        
        
        -- 2. Inherited Surrogate Keys (SCD2 Linkage)
        f.contract_no,
        dc.dim_debit_contract_key as debit_contract_history_key,
        f.sub_acco_no,
        s.dim_subaccount_key AS subaccount_history_key,
        f.cust_no,
        c.dim_customer_key AS customer_history_key,
        s.broker_cd,
        b.dim_broker_key AS broker_history_key,

        -- 3. Factual Metrics
        ${fact_cols.map(col => `f.${col}`).join(",\n        ")}

    FROM ${ref(source_layer, source_table)} AS f
    
    -- Dùng hàm joinHistory để lấy key từng đối tượng tại đúng ngày
    ${func.joinHistory(ref("silver", "dim_debit_contract"), "dc", "f.contract_no", "contract_no", "f.business_date")}
    ${func.joinHistory(ref("silver", "dim_subaccount"), "s", "f.sub_acco_no", "sub_acco_no", "f.business_date")}
    ${func.joinHistory(ref("silver", "dim_customer"), "c", "f.cust_no", "cust_no", "f.business_date")}
    ${func.joinHistory(ref("silver", "dim_broker"), "b", "s.broker_cd", "broker_cd", "f.business_date")}
    
    WHERE 
        ${incremental() 
          ? `f.${source_partition_col} = target_date` 
          : `f.${source_partition_col} BETWEEN start_date AND end_date`
        }
)

SELECT
    ${when(incremental(), `COALESCE(target._ingested_at, run_time)`, `run_time`)} AS _ingested_at,
    run_time AS _updated_at,
    stg.*
FROM staging_data AS stg
${when(incremental(), `LEFT JOIN ${self()} AS target ON stg.${hash_key_name} = target.${hash_key_name} AND target.${target_partition_col} = target_date`)}