config {
    type: "table",
    schema: "gold",
    name: "debit_contract_history",
    description: "Thông tin của hợp đồng nợ.",
    tags: ["gold", "debit_contract", "history"]
}

SELECT
    -- 0. Surrogate Key Mapping
    dc.dim_debit_contract_key AS debit_contract_history_key,

    -- 1. Core Debit Contract Attributes (From Silver)
    dc.contract_id,
    dc.allo_date,
    dc.ref_no,
    dc.parent_date,
    dc.parent_no,
    dc.sub_acco_no,
    dc.cust_group_id,
    dc.contr_date_from,
    dc.contr_date_to,
    dc.begin_int_date,
    dc.debit_type,
    dc.amount,
    dc.in_rate,
    dc.out_rate,
    dc.min_interest,
    dc.manager_in_rate,
    dc.manager_out_rate,
    dc.min_manager,
    dc.free_interest_days,
    dc.source_cd,
    dc.contract_type,
    dc.last_extend_date,
    dc.extend_count,
    dc.transaction_cd,
    dc.calucate,
    dc.decimal_point,
    dc.round_type,
    dc.int_config_id,
    dc.loan_type,
    dc.debttype_id,
    dc.int_type,
    dc.status,
    dc.remarks,
    dc.is_deleted,

    -- 2. Enriched Lookups (Translating codes to readable names)
    lkp_deb.attribute_name AS debit_type_name,
    lkp_con.attribute_name AS contract_type_name,
    lkp_loa.attribute_name AS loan_type_name,
    lkp_sts.attribute_name AS status_name,

    -- 3. Keys tới các đối tượng
    s.dim_subaccount_key as subaccount_history_key,
    s.sub_acco_no,
    c.dim_customer_key as customer_history_key,
    c.cust_no,
    b.dim_broker_key as broker_history_key,
    b.broker_cd,

    -- 4. Thông tin kĩ thuật SCD2
    dc.valid_from,
    dc.valid_to,
    dc.is_current,
    dc._ingested_at,
    dc._updated_at

FROM ${ref("silver", "dim_debit_contract")} AS dc

-- ==========================================
-- LOOKUP JOINS
-- ==========================================
LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_deb
    ON lkp_deb.category = 'MRGTDEBIT_CONTRACT__DEBIT_TYPE'
    AND dc.debit_type = lkp_deb.attribute_code
  
LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_con
    ON lkp_con.category = 'MRGTDEBIT_CONTRACT__CONTRACT_TYPE'
    AND dc.contract_type = lkp_con.attribute_code
  
LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_loa
    ON lkp_loa.category = 'MRGTDEBIT_CONTRACT__LOAN_TYPE'
    AND dc.loan_type = lkp_loa.attribute_code
  
LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_sts
    ON lkp_sts.category = 'MRGTDEBIT_CONTRACT__STATUS'
    AND dc.status = lkp_sts.attribute_code

-- ==========================================
-- TEMPORAL JOINS
-- ==========================================
${func.joinHistory(ref("silver", "dim_subaccount"), "s", "dc.sub_acco_no", "sub_acco_no", "DATE(dc.valid_from)")}
${func.joinHistory(ref("silver", "dim_customer"), "c", "s.cust_no", "cust_no", "DATE(dc.valid_from)")}
${func.joinHistory(ref("silver", "dim_broker"), "b", "s.broker_cd", "broker_cd", "DATE(dc.valid_from)")}

