config {
    type: "table",
    schema: "gold",
    name: "subaccount_history",
    description: "Lịch sử thông tin của tiểu khoản. Lưu ý: thông tin tại thời điểm valid_from, bất kì thay đổi nào ở các đối tượng bên ngoài (khách hàng, môi giới) sau valid_from sẽ không được phản ánh vào đây",
    tags: ["gold", "history", "subaccount", "daily"],
    bigquery: {
        partitionBy: 'DATE(valid_from)',
        clusterBy: ['is_current']
    },
    dependOnDependencyAssertions: true
}

js {
// ============================================================================
// BƯỚC 1: Config bảng dim nguồn từ silver
// ============================================================================
  const baseTable = {
    ref: ref("silver", "dim_subaccount"),
    alias: "t",
    columns: [ // Các array columns có thể chứa cả dạng "column_a as alias_b"
      "subaccount_history_key","sub_acco_no", "sub_acco_cd", "cust_group_id",
      "is_deleted", "acco_type","algos_type", "type_flg", "curr_cd", "bank_cd",
      "bank_branch_cd","bank_acco_number", "bank_acco_name", "bank_acco_id_no",
      "bank_flg","not_update_by_cust", "contract_no", "source_channel", "acco_sts",
      "acco_flg", "trade_acco_no", "status", "source_cd", "source_sname",
      "remarks", "open_date", "close_date", "reopen_date", "is_auto_advance",
      "is_auto_mortgage", "retention_rate", "warning_rate", "tn_rate",
      "call_rate", "withdraw_rate", "margin_limit_grp", "margin_limit"
    ],
    techColumns: ["valid_from", "valid_to", "is_current",]
  };
// ============================================================================
// BƯỚC 2: Config các bảng dim cần join để lấy history key
// ============================================================================
  const historyDimensions = [
    {
      ref: ref("silver", "dim_customer"),
      alias: "c",
      leftKey: "t.cust_no",
      rightKey: "cust_no",
      columns: ["customer_history_key", "cust_no"]
    },
    {
      ref: ref("silver", "dim_broker"),
      alias: "b",
      leftKey: "t.broker_cd",
      rightKey: "broker_cd",
      columns: ["broker_history_key", "broker_cd"]
    },
    {
      ref: ref("silver", "dim_transaction_office"),
      alias: "tr",
      leftKey: "b.transaction_cd",
      rightKey: "transaction_cd",
      columns: ["transaction_office_history_key", "transaction_cd"]
    }
  ];
// ============================================================================
// BƯỚC 3: Config các thuộc tính cần tra cứu giá trị
// ============================================================================
  const lookupAttributes = {
    algos_type:     "CORTSUB_ACCOUNT__ALGOS_TYPE",
    acco_type:      "CORTSUB_ACCOUNT__ACCO_TYPE",
    acco_sts:       "CORTSUB_ACCOUNT__ACCO_STS",
    status:         "CORTSUB_ACCOUNT__STATUS",
    source_channel: "CORTSUB_ACCOUNT__SOURCE_CHANNEL",
    bank_flg:       "CORTSUB_ACCOUNT__BANK_FLG"
  };

}

-- ============================================================================
-- LOGIC SQL (KHÔNG CẦN ĐỤNG VÀO)
-- ============================================================================
pre_operations {DROP TABLE IF EXISTS ${self()};}

SELECT
    -- Các trường từ bảng dim gốc
   ${func.renderColumns(baseTable.columns, baseTable.alias)},

   -- Các history key và natural key từ các đối tượng khác
    ${func.renderHistoryColumns(historyDimensions)}

    -- Giá trị tên thuộc tính sau khi lookup bảng dim_attribute_lookup
    ${func.renderLookupColumns(lookupAttributes)}

    -- Thông tin SCD7 từ bảng dim gốc
    ${baseTable.techColumns.map(col => `${baseTable.alias}.${col}`).join(",\n    ")}

FROM ${baseTable.ref} AS ${baseTable.alias}

-- Join để lấy history key
${historyDimensions.map(
    j => func.joinHistory(j.ref, j.alias, j.leftKey, j.rightKey, `DATE(${baseTable.alias}.valid_from)`)
).join("\n")}

-- Join để lookup giá trị tên thuộc tính
${Object.entries(lookupAttributes).map(([col, category]) => `LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_${col}
    ON lkp_${col}.category = '${category}'
    AND cast(${baseTable.alias}.${col} as STRING) = cast(lkp_${col}.attribute_code as STRING)`).join("\n\n")}