config {
    type: "incremental",
    schema: "gold",
    name: "subaccount_daily_asset_value",
    tags: ["gold", "asset_value", "fact"],
    uniqueKey: ["subaccount_daily_asset_value_key"],
    bigquery: {
        partitionBy: "business_date",
        clusterBy: ["sub_acco_no"]
    }
}

js {
  const source_layer = "silver";
  const source_table = "fact_subaccount_daily_asset_value";
  const source_partition_col = "business_date";
  const target_partition_col = "business_date";

  // Modification: Add const hash_key_name after defining join_date_col
  const hash_key_name = "subaccount_daily_asset_value_key";

  // Modification: fact_cols must not consist of field from dimensional entity
  const fact_cols = [
    "business_date", "is_deleted", "warning_level", "warning_num",
    "cash_amt", "sec_val", "sec_mrg_val", "sec_pending_val", "sec_mrg_pending_val", 
    "cash_pending_amt", "advance_amt", "bought_not_post_amt", "dividend_cash_amt", 
    "dividend_sec_val", "dividend_right_val", "other_asset_val", "debit_margin_amt", 
    "debit_coop_amt", "debit_debt_amt", "debit_mor_amt", "debit_other_amt", 
    "debit_temp_amt", "total_interest_amt", "debit_margin_expired", "debit_coop_expired", 
    "debit_mor_expired", "cash_block_amt", "credit_limit", "debt_interest_avail_payment", 
    "need_to_addition_cash", "need_to_addition_sec", "need_to_sell", "total_asset", 
    "total_mrg_asset", "total_debit", "margin_rate", "credit_cash_amt", "credit_sec_amt", 
    "t0_buy_amt", "t1_buy_amt", "t2_buy_amt", "t0_sell_amt", "t1_sell_amt", "t2_sell_amt", 
    "dividend_cash_market_amt", "dividend_sec_market_amt", "nav_bi"
  ];
}

pre_operations {
  -- 1. Declare biến
  DECLARE run_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP();
  DECLARE target_date DATE;
  DECLARE start_date DATE;
  DECLARE end_date DATE;

  -- 2. Xác định target_date, start_date, end_date
  ${incremental() 
    ? `SET target_date = ${dataform.projectConfig.vars.target_date 
        ? `DATE('${dataform.projectConfig.vars.target_date}')` 
        : `(SELECT MAX(${source_partition_col}) FROM ${ref(source_layer, source_table)})`
      };`
    : `SET start_date = ${dataform.projectConfig.vars.start_date 
        ? `DATE('${dataform.projectConfig.vars.start_date}')` 
        : `(SELECT MIN(${source_partition_col}) FROM ${ref(source_layer, source_table)})`
      };
      SET end_date = ${dataform.projectConfig.vars.end_date 
        ? `DATE('${dataform.projectConfig.vars.end_date}')` 
        : `(SELECT MAX(${source_partition_col}) FROM ${ref(source_layer, source_table)})`
      };
      SET target_date = NULL;`
  }
  -- 3. Xử lý Drop table khi full refresh để tránh lỗi schema thay đổi
  ${when(!incremental(),`DROP TABLE IF EXISTS ${self()};`)}
}

WITH staging_data AS (
    SELECT
        -- Modification: Use the hash key constant
        f.${hash_key_name},

        -- Measures from fact_cols
        ${fact_cols.map(col => `f.${col}`).join(",\n        ")},

        -- Entity Keys for Joins
        f.sub_acco_no,
        s.dim_subaccount_key AS subaccount_history_key,
        f.cust_no,
        c.dim_customer_key AS customer_history_key,
        s.broker_cd,
        b.dim_broker_key AS broker_history_key
        
    FROM ${ref(source_layer, source_table)} AS f
    
    -- Dùng hàm joinHistory để lấy key từng đối tượng tại đúng ngày
    ${func.joinHistory(ref("silver", "dim_subaccount"), "s", "f.sub_acco_no", "sub_acco_no", "f.business_date")}
    ${func.joinHistory(ref("silver", "dim_customer"), "c", "f.cust_no", "cust_no", "f.business_date")}
    ${func.joinHistory(ref("silver", "dim_broker"), "b", "s.broker_cd", "broker_cd", "f.business_date")}    
    WHERE 
        -- Switch between single date (incremental) and date range (full refresh)
        ${incremental() 
          ? `${source_partition_col} = target_date` 
          : `${source_partition_col} BETWEEN start_date AND end_date`
        }
)

SELECT
    ${when(incremental(), `COALESCE(target._ingested_at, run_time)`, `run_time`)} AS _ingested_at,
    run_time AS _updated_at,
    stg.*
FROM staging_data AS stg
${when(incremental(), `LEFT JOIN ${self()} AS target ON stg.${hash_key_name} = target.${hash_key_name} AND target.${target_partition_col} = target_date`)}