config {
    type: "table",
    schema: "gold",
    name: "subaccount_history",
    description: "Lịch sử thông tin của tiểu khoản. Lưu ý: thông tin tại thời điểm valid_from, bất kì thay đổi nào ở các đối tượng bên ngoài (khách hàng, môi giới) sau valid_from sẽ không được phản ánh vào đây",
    tags: ["gold", "subaccount", "history"],
    bigquery: {
        partitionBy: 'DATE(valid_from)',
        clusterBy: ['is_current']
    }
}

SELECT
    -- 0. Surrogate Key Mapping
    s.dim_subaccount_key AS subaccount_history_key,

    -- 1. Core Subaccount Attributes (From Silver)
    s.sub_acco_no,
    s.sub_acco_cd,
    s.cust_group_id,
    s.is_deleted,
    s.acco_type,
    s.algos_type,
    s.type_flg,
    s.curr_cd,
    s.bank_cd,
    s.bank_branch_cd,
    s.bank_acco_number,
    s.bank_acco_name,
    s.bank_acco_id_no,
    s.bank_flg,
    s.not_update_by_cust,
    s.contract_no,
    s.source_channel,
    s.acco_sts,
    s.acco_flg,
    s.trade_acco_no,
    s.status,
    s.source_cd,
    s.source_sname,
    s.remarks,
    s.open_date,
    s.close_date,
    s.reopen_date,
    s.is_auto_advance,
    s.is_auto_mortgage,
    s.retention_rate,
    s.warning_rate,
    s.tn_rate,
    s.call_rate,
    s.withdraw_rate,
    s.margin_limit_grp,
    s.margin_limit,

    -- 2. Tên các attribute được số hóa
    lkp_alg.attribute_name AS algos_type_name,
    lkp_type.attribute_name AS acco_type_name,
    lkp_ast.attribute_name AS acco_sts_name,
    lkp_sts.attribute_name AS status_name,
    lkp_src.attribute_name AS source_channel_name,
    lkp_bnk.attribute_name AS bank_flg_name,

    -- 3. Keys dắt tới broker và customer
    b.dim_broker_key as broker_history_key,
    s.broker_cd,
    b.transaction_cd,
    c.dim_customer_key as customer_history_key,
    c.cust_no,

    -- 4. Thông tin kĩ thuật SCD2
    s.valid_from,
    s.valid_to,
    s.is_current,
    s._ingested_at,
    s._updated_at

FROM ${ref("silver", "dim_subaccount")} AS s

-- ==========================================
-- LOOKUP JOINS
-- ==========================================
LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_type 
    ON lkp_type.category = 'CORTSUB_ACCOUNT__ACCO_TYPE'
    AND s.acco_type = lkp_type.attribute_code

LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_sts
    ON lkp_sts.category = 'CORTSUB_ACCOUNT__STATUS'
    AND s.status = lkp_sts.attribute_code

LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_src
    ON lkp_src.category = 'CORTSUB_ACCOUNT__SOURCE_CHANNEL'
    AND s.source_channel = lkp_src.attribute_code

LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_bnk
    ON lkp_bnk.category = 'CORTSUB_ACCOUNT__BANK_FLG'
    AND s.bank_flg = lkp_bnk.attribute_code

LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_ast
    ON lkp_ast.category = 'CORTSUB_ACCOUNT__ACCO_STS'
    AND s.acco_sts = lkp_ast.attribute_code

LEFT JOIN ${ref("silver", "dim_attribute_lookup")} AS lkp_alg
    ON lkp_alg.category = 'CORTSUB_ACCOUNT__ALGOS_TYPE'
    AND s.algos_type = lkp_alg.attribute_code

-- ==========================================
-- TEMPORAL JOINS
-- ==========================================

LEFT JOIN ${ref("silver", "dim_customer")} AS c
    ON s.cust_cd = c.cust_cd
    AND s.valid_from >= c.valid_from
    AND (c.valid_to IS NULL OR s.valid_from < c.valid_to)

LEFT JOIN ${ref("silver", "dim_broker")} AS b
    ON s.broker_cd = b.broker_cd
    AND s.valid_from >= b.valid_from
    AND (b.valid_to IS NULL OR s.valid_from < b.valid_to)